apiVersion: argoproj.io/v1alpha1

kind: Application
metadata:
  name: ingress-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rakshithrpoojary/helm.git
    targetRevision: HEAD
    path: charts/Ingress
    helm:
      valueFiles:
        - ../../environments/dev/ingress-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommercesecond
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true