apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  labels:
    role: {{ .Values.frontend.labels.role }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: {{ .Values.frontend.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      role: {{ .Values.frontend.labels.role }}
  template:
    metadata:
      labels:
        role: {{ .Values.frontend.labels.role }}
    spec:
      serviceAccountName: secretmanager
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true
          imagePullPolicy: Always
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "my-secrets"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
  strategy:
    blueGreen:
      activeService: frontend-active
      previewService: frontend-preview
      autoPromotionEnabled: true