apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
spec:
  ports:
    - port: {{ .Values.frontend.previewservice.port }}
      targetPort: {{ .Values.frontend.previewservice.targetPort }}
      protocol: TCP
  type: {{ .Values.frontend.previewservice.type }}
  selector:
    role: {{ .Values.frontend.labels.role }}
