apiVersion: v1
kind: Service
metadata:
  name: frontend-active
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  type: {{ .Values.frontend.service.type }}
  selector:
    role: {{ .Values.frontend.labels.role }}
