apiVersion: v1
kind: Service
metadata:
  name: frontend-active
spec:
  ports:
    - port: {{ .Values.frontend.activeservice.port }}
      targetPort: {{ .Values.frontend.activeservice.targetPort }}
      protocol: TCP
  type: {{ .Values.frontend.activeservice.type }}
  selector:
    role: {{ .Values.frontend.labels.role }}
