apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    role: {{ .Values.backend.labels.role }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: {{ .Values.backend.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.backend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.backend.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      role: {{ .Values.backend.labels.role }}
  template:
    metadata:
      labels:
        role: {{ .Values.backend.labels.role }}
    spec:
      serviceAccountName: secretmanager
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true
          imagePullPolicy: Always
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "my-secrets"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}