apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  type: {{ .Values.backend.service.type }}
  selector:
    role: {{ .Values.backend.labels.role }}