apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.headlessService.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mongo.headlessService.port }}
      targetPort: {{ .Values.mongo.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.mongo.appLabel }}