backend:

  replicaCount: 1

  image:
    repository: 784318224800.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: "7"
    pullPolicy: Always

  containerPort: 4000

  service:
    type: ClusterIP
    port: 80
    targetPort: 4000

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%

  labels:
    role: backend