frontend:

  replicaCount: 1

  image:
    repository: 518283888975.dkr.ecr.ap-south-1.amazonaws.com/chat-frontend
    tag: "18"
    pullPolicy: Always

  containerPort: 80

  previewservice:
    type: LoadBalancer
    port: 80
    targetPort: 80
    
  activeservice:
    type: ClusterIP
    port: 80
    targetPort: 80

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  labels:
    role: frontend