frontend:

  replicaCount: 5

  image:
    repository: 784318224800.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: "7"
    pullPolicy: Always

  containerPort: 80

  previewservice:
    type: LoadBalancer
    port: 80
    targetPort: 80

  activeservice:
    type: ClusterIP
    port: 80
    targetPort: 80

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  labels:
    role: frontend