ingress:
  enabled: true
  name: mainlb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

  className: alb

  paths:
    - path: /api
      service: backend
      port: 80

    - path: /
      service: frontend-active
      port: 80

    - path: /frontend-preview
      service: frontend-preview
      port: 80