ingress:
  enabled: true
  name: mainlb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:784318224800:certificate/fc1cdce8-a463-43d2-a5c6-a66d6b10dd18
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"

  className: alb

  paths:
    - path: /api
      service: backend
      port: 80

    - path: /
      service: frontend-active
      port: 80

    - path: /frontend-preview
      service: frontend-preview
      port: 80